### PR TITLE
Bundle and transpile sources to ES2015 + Fix undefined methods

### PR DESCRIPTION
**Pull request by johartl**
This PR addresses two things
- Your sources still needed to be compiled to ES5. I added the `postinstall` hook to your package.json which bundles and transpiles your sources before the package is installed.
- There were some undefined method references (`updateMap`, `setPokemonOnMap` and `showSideBar`)

### CODE REVIEW

**Comment by WoH** [comment]
Unlucky

**Comment by johartl** [comment]
What's the reason for closing this?

**Comment by WoH** [comment]
Otherwise you'll have to get of the ES6 parts btw. I'm not sure why you're doing ES5 with like 2 lines of ES6 anyway. That's not to say that you shouldn't bundle anyway. 

If you're not a fan of us fixing your project, we will have to keep forking your repo, fixing it and you'll have to manually integrate these. I for myself won't do PR's if you close them without reasoning.

**Comment by farisca** [comment]
Sorry, it was my fault. I mistakenly closed it :(

**Pull request merged**
